version: "3.7"
services:
  server:
    build: ./server/nodejs
    # environment:
    #   - APP_SERVER_PORT=${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    # ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/nodejs/src:/srv/app/home-server/src
    command: npm run devstart
    networks:
      - traefik
      - cv
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.cv_server.loadbalancer.server.port=${SERVER_PORT}
    #   - traefik.docker.network=traefik
  client:
    build: ./client/reactjs
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    # ports:
    #   - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/reactjs/src:/srv/app/home-client/src
      - ./client/reactjs/public:/srv/app/home-client/public
    links:
      - server
    command: npm run start
    networks:
      - traefik
      - cv
    labels:
      - traefik.enable=true
      - traefik.http.routers.cv_client.rule=Host(`cv.jeffslord.com`)
      - traefik.http.services.cv_client.loadbalancer.server.port=${CLIENT_PORT}
      - traefik.docker.network=traefik

networks:
  traefik:
    external: true
  cv:
    driver: bridge