version: "3"
services:
  cv_server:
    build: ./server/nodejs
    volumes:
      - ./server/nodejs/src:/srv/app/home-server/src
  cv_client:
    build: ./client/reactjs
    volumes:
      - ./client/reactjs/src:/srv/app/home-client/src
      - ./client/reactjs/public:/srv/app/home-client/public