version: "3"
services:
  server:
    build: ./server/nodejs
    # expose:
    # - port
    # environment:
    # API_HOST: ${API_HOST}
    # APP_SERVER_PORT: ${APP_SERVER_PORT}
    # ports:
    # - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    # volumes:
    # -
